import Head from 'next/head'

export default function Home() {
  return (
    <div>
      <Head>
        <title>The Indoor Jungle Project</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
 front page test

   
    </div>
  )
}
